import { 
  Home, 
  Upload, 
  History, 
  User, 
  Landmark, 
  TrendingUp, 
  Verified, 
  PlusCircle, 
  ArrowRight, 
  BookOpen, 
  MessageSquare, 
  ShieldCheck, 
  FileText, 
  CheckCircle2, 
  AlertCircle, 
  Search, 
  MoreHorizontal, 
  Download, 
  Send, 
  Edit3, 
  ChevronLeft, 
  ChevronRight,
  ChevronDown,
  Calculator, 
  Activity, 
  Lock, 
  Eye, 
  EyeOff, 
  ShieldAlert, 
  Fingerprint, 
  RefreshCcw, 
  Terminal, 
  Cpu, 
  Zap, 
  Camera, 
  Shield, 
  File, 
  Check, 
  Library,
  X
} from 'lucide-react';

export const ICONS = {
  Home,
  Upload,
  History,
  User,
  Landmark,
  TrendingUp,
  Verified,
  PlusCircle,
  ArrowRight,
  BookOpen,
  MessageSquare,
  ShieldCheck,
  FileText,
  CheckCircle2,
  AlertCircle,
  Search,
  MoreHorizontal,
  Download,
  Send,
  Edit3,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Calculator,
  Activity,
  Lock,
  Eye,
  EyeOff,
  ShieldAlert,
  Fingerprint,
  RefreshCcw,
  Terminal,
  Cpu,
  Zap,
  Camera,
  Shield,
  File,
  Check,
  Library,
  X,
  // Aliases for historical compatibility
  Bank: Landmark,
  Trending: TrendingUp,
  Plus: PlusCircle,
  Info: AlertCircle,
  Advocate: MessageSquare,
  AILogo: Activity,
  Edit: Edit3
};

/** Neutral placeholder avatar (no expressive stock face) when the user has no photo. */
export const DEFAULT_AVATAR_SRC =
  'data:image/svg+xml,' +
  encodeURIComponent(
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 96" role="img" aria-label="Profile"><rect width="96" height="96" rx="28" fill="#f0eeea"/><ellipse cx="48" cy="38" rx="18" ry="20" fill="#d5d2cb"/><ellipse cx="48" cy="82" rx="26" ry="16" fill="#d5d2cb"/></svg>',
  );

export const THEME = {
  colors: {
    primary: '#00236f',
    secondary: '#006c49',
    tertiary: '#735c00',
    background: '#f7f9fb',
    text: '#191c1e',
    textVariant: '#444651'
  }
};
